#!/usr/bin/env bash
set -e

export KAFKA_LISTENERS="PLAINTEXT://0.0.0.0:${KAFKA_PORT:-10000}"
export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${RENDER_KAFKA_HOST:-kafka}:${KAFKA_PORT:-10000}"
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT"
export KAFKA_INTER_BROKER_LISTENER_NAME="PLAINTEXT"

exec /etc/confluent/docker/run
